# Generated by Django 6.1.1 on 2026-10-05 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('categoria', models.CharField(choices=[('Novela', 'Novela'), ('Ciencia', 'Ciencia'), ('Historia', 'Historia'), ('Tecnologia', 'Tecnología'), ('Infantil', 'Infantil'), ('General', 'General')], default='General', max_length=50, verbose_name='Categoría')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='libros_pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento PDF / Ficha')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Stock Disponible')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='socios/', verbose_name='Foto de Perfil')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('estado', models.CharField(choices=[('Prestado', 'Prestado'), ('Devuelto', 'Devuelto'), ('Atrasado', 'Atrasado')], default='Prestado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro', verbose_name='Libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
